# Generated by Django 4.0.3 on 2022-03-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empower',
            name='user_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
